services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./app
        target: /usr/src/app
      - node_modules:/usr/src/app/react-app/node_modules
    #"react-app"の部分がプロジェクト名になる
    command: sh -c "cd react-app && yarn start" 
    ports:
      - 3000:3000
    stdin_open: true #標準入力をコンテナと紐付ける
volumes:
  node_modules: